from sentence_transformers import SentenceTransformer
import faiss
import numpy as np
import pandas as pd
import requests
import json

# Load CSV
df = pd.read_csv("transaksi.csv", sep=";")
df.columns = df.columns.str.strip()
df['Tanggal'] = pd.to_datetime(df['Tanggal'], dayfirst=True)

# Buat "context string" dari setiap baris
contexts = []
for idx, row in df.iterrows():
    context = f"Tanggal: {row['Tanggal'].strftime('%d-%m-%Y')}, Jenis: {row['Jenis']}, Kategori: {row['Kategori']}, Jumlah: {row['Jumlah']}, Deskripsi: {row['Deskripsi']}"
    contexts.append(context)

# Buat embeddings
model = SentenceTransformer('all-MiniLM-L6-v2')
embeddings = model.encode(contexts, show_progress_bar=True)

# Buat index FAISS
dimension = embeddings.shape[1]
index = faiss.IndexFlatL2(dimension)
index.add(np.array(embeddings))

# Pertanyaan user
pertanyaan = input("Masukkan pertanyaan akuntansi: ")

# Buat embedding pertanyaan
query_embedding = model.encode([pertanyaan])

# Cari top-k context relevan
k = 5
D, I = index.search(np.array(query_embedding), k)

# Ambil context relevan
retrieved_contexts = [contexts[i] for i in I[0]]

# Gabungkan context menjadi 1 string
# PROMPT PERLU REVISI!
context_string = "\n".join(retrieved_contexts)

prompt = f"""
Kamu adalah asisten data accounting.

Berikut adalah beberapa data transaksi relevan:
{context_string}

File CSV memiliki kolom: Tanggal (datetime), Jenis (Pemasukan/Pengeluaran), Kategori, Jumlah (int), Deskripsi.
Buatkan satu baris kode Python pandas untuk menjawab pertanyaan berikut dengan cara:
- Memfilter sesuai pertanyaan
- Mengambil kolom ['Tanggal', 'Deskripsi', 'Jumlah']
- Menyimpan hasil filter ke variabel 'jawaban'
- Menghitung total 'Jumlah' dari hasil filter dan menyimpannya ke variabel 'total'

Pastikan:
- Menggunakan df yang sudah tersedia
- Hanya kirim satu baris kode tanpa penjelasan, awali hanya dengan jawaban kode

Pertanyaan: "{pertanyaan}"
"""

response = requests.post(
    'http://localhost:11434/api/generate',
    json={"model": "llama3", "prompt": prompt},
    stream=True
)

result = ""
for chunk in response.iter_lines():
    if chunk:
        try:
            data = json.loads(chunk.decode('utf-8'))
            if 'response' in data:
                result += data['response']
        except Exception:
            continue

result = result.strip().strip('`').replace('```python', '').replace('```', '').strip()

print("\n=== Kode Generated by LLaMA ===")
print(result)

exec_globals = {'df': df, 'pd': pd}
exec(result, exec_globals)
jawaban = exec_globals.get('jawaban', None)

if jawaban is not None and not jawaban.empty:
    print(jawaban)
else:
    print("Tidak ada transaksi relevan")


